#!/bin/sh
BACKGROUND_FILE=background_1024x600.png
if [ -e /tmp/use_ugly_x_cursor ]; then
  BACKGROUND_FILE=background_1024x600_retro.png
fi

WM=/usr/bin/chromeos-wm
IMAGES=/usr/share/chromeos-assets/images
BACKGROUND="${IMAGES}/${BACKGROUND_FILE}"
LOG_DIR="${HOME}/logs"
CHROME_COMMAND="/usr/bin/chromeos-chrome"
XTERM_COMMAND="/usr/bin/xterm -bg black -fg grey"

# xdg-open is used to open downloaded files.
# It runs sensible-browser, which uses $BROWSER.
export BROWSER=/usr/bin/chromeos-chrome

/usr/bin/xscreensaver -no-splash &

exec "${WM}"                                        \
    --hotkey_overlay_image_dir="${IMAGES}"            \
    --panel_anchor_image="${IMAGES}/panel_anchor.png" \
    --panel_bar_image="${IMAGES}/panel_bar_bg.png"    \
    --shadow_image_dir="${IMAGES}"                    \
    --wm_background_image="${BACKGROUND}"             \
    --wm_chrome_command="${CHROME_COMMAND}"           \
    --wm_xterm_command="${XTERM_COMMAND}"           \
    --wm_spawn_chrome_on_start=true                   \
    --v=1                                             \
    --log_dir="${LOG_DIR}"
