# -*- python -*-

# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os

env = Environment()


env.Append(
    CPPPATH=['../..', '../../../third_party/chrome/files', '../../base'],
    CCFLAGS=['-g', '-fno-exceptions', '-Wall', '-Werror'],
    LIBPATH=['../../base', '../../../common'],
    LIBS=['base', 'pam', 'pam_misc', 'gflags'],
)

env.Append(LIBS=File('../../base/libbase.a'))
env.ParseConfig('pkg-config --cflags --libs glib-2.0')

#sources = env.Split("""test_login.cc""")

main = ['test_login.cc']

env.Program('test-login', main)
