# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import os

Help('''\
Type: 'scons' to build\
''')

env = Environment()

# Pull in tool overrides from the environment to enable cross-compile.
for key in Split('CC CXX AR RANLIB LD NM CFLAGS CCFLAGS'):
  value = os.environ.get(key)
  if value != None:
    env[key] = value
if not env.has_key('CCFLAGS'):
  env['CCFLAGS'] = '-Wall -Werror -O3'
env.Append(CCFLAGS=' -I..')
env['LINKFLAGS'] = '-lgflags -lprotobuf -lgtest'

# Fix up the pkg-config path if it is present in the environment.
if os.environ.has_key('PKG_CONFIG_PATH'):
  env['ENV']['PKG_CONFIG_PATH'] = os.environ['PKG_CONFIG_PATH']

env.ParseConfig('pkg-config --cflags --libs libglog libpcrecpp')

srcs = Split('''\
  strutil.cc
''')

base = env.StaticLibrary('base', srcs)

