#!/bin/sh
# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

set -e
PKG=chromeos-cryptohome
CFG=pam_mount.conf.xml
case "$1" in
    remove)
      dpkg-divert --package ${PKG} --remove \
                  --rename /etc/security/${CFG}
    ;;
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
