# Copyright (c) 2009 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

#/

default::	

all::	

install::	
	mkdir -p $(DESTDIR)/etc/pam.d
	install -m644 xscreensaver $(DESTDIR)/etc/pam.d/

clean::

