#!/bin/bash

set -e

if [ -z $1 ] 
then
  echo "Usage: $0 localaccount_username"
  exit 1
fi

echo "Enabling local account.  Remove chromeos_pam_localaccount.h to disable."

cat <<EOF > pam_localaccount.h
// lcoal username for Chrome OS pam
// This file is auto-generated by enable_localaccount.sh

#ifndef CHROMEOS_PAM_LOCALACCOUNT_H_
#define CHROMEOS_PAM_LOCALACCOUNT_H_

namespace chromeos_pam {
const char kLocalAccount[] = "$1";
}

#endif // CHROMEOS_PAM_LOCALACCOUNT_H_
EOF
