#!/bin/bash

# Copyright (c) 2010 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# chromeos-cryptohome.preinst

set -e

PKG=chromeos-cryptohome
CFG=pam_mount.conf.xml
dpkg-divert --admindir "${ROOT}/var/lib/dpkg" --add --package ${PKG} --rename \
                    --divert /etc/security/$CFG.chromeos-orig /etc/security/$CFG
